### ISSUE TITLE
Error at initial configuration

### ISSUE THREAD

**Issue by hathagat** [hoellen/docker-nextcloud#39]
Hi,

first of all thank you for the awesome image!

I tried to setup a fresh installation but ran into an error.
Log output:
```
Enabling Snuffleupagus...
Starting automatic configuration...
Automatic configuration finished.
Nextcloud is not installed - only a limited number of commands are available


There are no commands defined in the "app" namespace.  
                                             

Exception: Not installed in /nextcloud/lib/base.php:281
Stack trace:
#0 /nextcloud/lib/base.php(697): OC::checkInstalled(Object(OC\SystemConfig))
#1 /nextcloud/lib/base.php(1164): OC::init()
#2 /nextcloud/cron.php(43): require_once('/nextcloud/lib/...')
#3 {main}
{
  "reqId": "3R5ysfM84Jmj0g3oWsdQa",
  "level": 3,
  "time": "2023-04-15T20:56:53+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "cron",
  "method": "",
  "url": "--",
  "message": "Not installed",
  "userAgent": "--",
  "version": "",
  "exception": {
    "Exception": "Exception",
    "Message": "Not installed",
    "Code": 0,
    "Trace": [{
      "file": "/nextcloud/lib/base.php",
      "line": 697,
      "function": "checkInstalled",
      "class": "OC",
      "type": "::",
      "args": [
        ["OC\\SystemConfig"]
      ]
    }, {
      "file": "/nextcloud/lib/base.php",
      "line": 1164,
      "function": "init",
      "class": "OC",
      "type": "::",
      "args": []
    }, {
      "file": "/nextcloud/cron.php",
      "line": 43,
      "args": ["/nextcloud/lib/base.php"],
      "function": "require_once"
    }],
    "File": "/nextcloud/lib/base.php",
    "Line": 281,
    "CustomMessage": "--"
  }
}
```

I found some somewhat related issues ([1](https://github.com/hoellen/docker-nextcloud/issues/10), [2](https://github.com/nextcloud/server/issues/37406), [3](https://github.com/linuxserver/docker-nextcloud/issues/280)) but still can't get it to work.
Any idea what's going wrong?

**Comment by louis-prudhomme** [comment]
Hey ! Have you tried accessing the Nextcloud web UI ? It should prompt you with options to install Nextcloud.

**Comment by hathagat** [comment]
Hi, thanks for your suggestion! I tried that already. No UI for me. However, I don't think any UI is available at this point of installation anyway.

**Comment by calcanthum** [comment]
Still having the same issue using the latest package. Also no UI available, and I tried to re-run /usr/local/bin/setup.sh but that didn't resolve the issue.

**Comment by hoellen** [comment]
In order for someone to help you, more information is needed:
- Are you using `docker-compose.yml` or plain docker command? 
- What is your start command or your `docker-compose.yml` file?
- What database are you trying to run?
- What are your environment variables?
- What is the definition of the volumes?
- ...

**Comment by hoellen** [comment]
Since there are no additional details since two year, I will close this one. Feel free to reopen.
